I  moved the package
mkrtichstepanyan/qa_trainings pull request #39
Opened 2022-03-31 14:52 UTC by AnjelaMelqonyan

2022-04-01 14:44 UTC, mkrtichstepanyan requested changes

2022-04-01 14:44 UTC, mkrtichstepanyan commented on src/main/java/arrays/homework_3/anjela_melqonyan/SortingAlgorithms.java
> +
Remove unnecessary  lines

2022-04-02 16:17 UTC, AnjelaMelqonyan commented on src/main/java/arrays/homework_3/anjela_melqonyan/SortingAlgorithms.java
> +
Done

2022-04-06 17:39 UTC, mkrtichstepanyan approved these changes

2022-04-06 17:39 UTC, merged